### ISSUE TITLE
Unable to retry requests when content is not null

### ISSUE THREAD

**Issue by Jericho** [Pathoschild/FluentHttpClient#60] opened 2017-09-03 18:12 UTC
The [PR I submitted in January 2017](https://github.com/Pathoschild/FluentHttpClient/commit/3e6481f8cdcaa5efdab4eb8936d8ecb839f80217
) to introduce 'retry' functionality included an extension method to clone the `HttpRequestMessage` before dispatching it to avoid `The request message was already sent. Cannot send the same request message multiple times..` exception when re-attempting to dispatch the request.

This extension method works fine for scenarios where a request does not have any body content, such as a GET for example, but for scenarios like POST which typically have content in the body, the extension method does not work properly.

When the request is dispatched for the second time, you get a `Cannot access a disposed object.` exception which is due to the fact that the content stream is automatically disposed after the initial request.

The solution is to make sure to clone the content (if any) when cloning the request.

I will submit a PR shortly with the solution.

**Comment by Pathoschild** [comment] 2017-09-10 01:10
@Jericho I added a unit test which resubmits a stream-content request, but I can't reproduce that error. Can you check if there's a specific case where it happens (e.g. if using a stream other than `MemoryStream`?) I want to make sure the unit tests cover that case.

**Comment by Jericho** [comment] 2017-09-10 02:44
I haven't been able to reproduce this issue in a unit test using `RichardSzalay.MockHttp`. The only way I was able to consistently reproduce was in an integration test where I issue a request to an actual api that returns a HTTP status code that my client determines requires a retry. In my integration test, I can reproduce the exception 100% of the time and the solution in this PR solves the problem 100% of the time.

**Comment by Jericho** [comment] 2017-09-10 02:50
I'm guessing there's a slight difference between how mockHttp issues request and how the real HttpClient issues requests but I haven't been able to pinpoint the difference.

**Comment by Jericho** [comment] 2017-09-10 03:23
I just opened an [issue with the `MockHttp` project](https://github.com/richardszalay/mockhttp/issues/54) to help me understand why we can't reproduce this problem with a mock http client.

**Comment by Pathoschild** [comment] 2017-09-10 08:03
Seems like an upstream problem, so I'll leave the unit test as-is and close this. We can update later if they release a new version which fixes the unit test quirk.

**Closed as completed by Pathoschild** 2017-09-10 08:03 UTC
Labels: bug
